### ISSUE TITLE
sif-1000 Testnet任务

### ISSUE THREAD

**Issue by StrawberryFlavor** [hashgard/testnets#1]
任务列表：[https://github.com/hashgard/testnets/tree/master/sif/sif-1000](https://github.com/hashgard/testnets/tree/master/sif/sif-1000) 。请回复证据。

**Comment by StrawberryFlavor** [comment]
GitHub ID: StrawberryFlavor
Task 1: 无
Task 2: http://132.232.161.69:26657/status
Task 3: gardvaloper1zctuqcxwdpfj0ss0s53rzcpae7j480r864sxjh
Task 4: 8DC1DC6F45CA2D652BF14CCFA4EBFACB2DD26203403010A3FDA5AF8E0AC46727
Task 5: C32323B5A58EC679F16C1FDEA3C2740680D1C577F63E4FD1057D75B2FBC2A573
Task 6:

**Comment by jeromelinjianlong** [comment]
GitHub ID: jeromelinjianlong
Task 1: 无
Task 2: http://113.111.5.97:26657/status
Task 3: gardvaloper1xstxnlykpav68384a5ezfdsluus4duuqc4ylun
Task 4: 2DB2540CCB60856B7CABE83865E1F31B251BE47A5191D372991ABC5119B14D47
Task 5: B0072380558E3FE531B4D5DACFDFCEA3553109F0C2989C6DEA7F786B2EC01CC8
Task 6: 7426E67F8A1B2E08466AD5E070E63A56055E1EB8E62DB932BA2BE530D27646C5

**Comment by Peoley199** [comment]
GitHub ID:Peoley199
Task 1: 无
Task 2: http://61.130.11.178:26657/status
Task 3: gardvaloper1ce52pu94qte24v0uepgaz22xyva97se2w3z3ep
Task 4: 9859F065EF39E1CDC6C86DF2DDA451902BDFD7C2ACBFD2EE1F2F08AB5F590AF6
Task 5:
send1:A50C709039E22B4F5D9BFF5160C7D00BB99BCFDDD3FD6558D0754D31FCEBADFA
send2:8CBB8D3FCF93FFEBF710944A5A1441B2A3AA32F3FF9BBDB9A67F018C7D6A5B75
Task 6: C1D1B58EFBE85065933320F6E5507FA7420C751A71D10A3B3F1547106494866C

**Comment by 101615** [comment]
GitHub ID: 101615
Task 1: 无
Task 2: http://113.111.5.97:26657/status
Task 3: gardvaloper1xmtx28j2x62q4704xjmqzqywapuwq73x3y38f8
Task 4: F23EDFF0799B52FCFC032BD197E4F46D1D2B5C698B25322BFA75B8A4BA5A9192
Task 5: 41C401A36592E33EE4F05926BE5E157D6047A2AAF1AB2E2D4A3D9AF13C528202
Task 6: 361D89BB0DDF8C39519CA33CA1AF7F3F9A014AB103295084BC6788A2A485998D
