### ISSUE TITLE
委托任务  重新委托报错

### ISSUE THREAD

**Issue by Peoley199** [hashgard/testnets#13]
## Summary of Bug （缺陷概述）
 
 
委托任务：钱包 B 通过 redelegate 操作，将委托的10 gard 从自己创建的验证人转移至官方验证人操作时报错，没有正常转移
## Steps to Reproduce （复现步骤）
 
 
[root@172 ~]# hashgardcli stake delegate gardvaloper1supcm47en5p9pr8mjx9h77mceekmtrnt0pr4wf 10gard --from=Peoley --fees=1gard --chain-id=sif-4000
{"chain_id":"sif-4000","account_number":"27","sequence":"4","fee":{"amount":[{"denom":"gard","amount":"1"}],"gas":"200000"},"msgs":[{"type":"cosmos-sdk/MsgDelegate","value":{"delegator_address":"gard1supcm47en5p9pr8mjx9h77mceekmtrntarwa7y","validator_address":"gardvaloper1supcm47en5p9pr8mjx9h77mceekmtrnt0pr4wf","value":{"denom":"gard","amount":"10"}}}],"memo":""}

confirm transaction before signing and broadcasting [Y/n]: y
Password to sign with 'Peoley':
{
 "height": "91735",
 "txhash": "1DED8F2A017F96C4B636EA057656B4AEAC3037AB40E29B09AE1898888C1DB142",
 "logs": [
  {
   "msg_index": "0",
   "success": true,
   "log": ""
  }
 ],
 "gas_wanted": "200000",
 "gas_used": "88021",
 "tags": [
  {
   "key": "action",
   "value": "delegate"
  },
  {
   "key": "delegator",
   "value": "gard1supcm47en5p9pr8mjx9h77mceekmtrntarwa7y"
  },
  {
   "key": "destination-validator",
   "value": "gardvaloper1supcm47en5p9pr8mjx9h77mceekmtrnt0pr4wf"
  }
 ]
}
[root@172 ~]# hashgardcli stake redelegate gardvaloper1supcm47en5p9pr8mjx9h77mceekmtrnt0pr4wf gardvaloper17dvu8yt47mq0k0tj50rr46ke6yh4g8dzvvld6l 10 --chain-id=sif-4000 --from=Peoley --gas=auto
gas estimate: 133757
{"chain_id":"sif-4000","account_number":"27","sequence":"5","fee":{"amount":null,"gas":"133757"},"msgs":[{"type":"cosmos-sdk/MsgBeginRedelegate","value":{"delegator_address":"gard1supcm47en5p9pr8mjx9h77mceekmtrntarwa7y","validator_src_address":"gardvaloper1supcm47en5p9pr8mjx9h77mceekmtrnt0pr4wf","validator_dst_address":"gardvaloper17dvu8yt47mq0k0tj50rr46ke6yh4g8dzvvld6l","shares_amount":"10.000000000000000000"}}],"memo":""}

confirm transaction before signing and broadcasting [Y/n]: y
Password to sign with 'Peoley':
{
 "height": "91779",
 "txhash": "FAEB8480E971B7C6A92B4DE34004BDBE205D6CBD11B3D300CF944425B614C41D",
 "code": 12,
 "gas_wanted": "133757",
 "gas_used": "133787",
 "codespace": "sdk"
}
ERROR: {"codespace":"sdk","code":12,"message":"out of gas in location: WritePerByte; gasWanted: 133757, gasUsed: 133787"}
[root@172 ~]# hashgardcli stake redelegate gardvaloper1supcm47en5p9pr8mjx9h77mceekmtrnt0pr4wf gardvaloper17dvu8yt47mq0k0tj50rr46ke6yh4g8dzvvld6l 10gard --chain-id=sif-4000 --from=Peoley --gas=auto
ERROR: ERROR:
Codespace: sdk
Code: 6
Message: "bad string to integer conversion, combinedStr: 10gard000000000000000000"
____
#### For Admin Use （管理员专用）
 - [x] Not duplicate issue
 - [ ] Appropriate labels applied
 - [ ] Appropriate contributors tagged
 - [ ] Contributor assigned/self-assigned

**Comment by hashgard-victor** [comment]
已将文档调整为hashgardcli sif-4000 帮助命令
