### ISSUE TITLE
When start hashgard show error

### ISSUE THREAD

**Issue by wjdfx** [hashgard/testnets#14]
## Summary of Bug （缺陷概述）
 
 

When I run hashgard binary command:
./hashgard start --home=/mnt/data/hashgard

The screen show error:

I[2019-04-26|14:21:03.568] Starting ABCI with Tendermint                module=main
ERROR: Error during handshake: Error on replay: Validator set is nil in genesis and still empty after InitChain

I already replace the config.tml & genesis.json file. config folder include 5 files:

config.toml  gaiad.toml  genesis.json  node_key.json  priv_validator_key.json

## Steps to Reproduce （复现步骤）
 
 

already double check genesis.json is right.
https://raw.githubusercontent.com/hashgard/testnets/master/sif/sif-4000/config/genesis.json
____
#### For Admin Use （管理员专用）
 - [ ] Not duplicate issue
 - [ ] Appropriate labels applied
 - [ ] Appropriate contributors tagged
 - [ ] Contributor assigned/self-assigned

**Comment by yangyanqing** [comment]
Could you please paste all commands in your steps here ?

**Comment by wjdfx** [comment]
unsafe-reset-all solved it.
