### ISSUE TITLE
建议正式版本对slash的miss块数值进行调整

### ISSUE THREAD

**Issue by wjdfx** [hashgard/testnets#15]
## Summary（摘要）
 
 

目前sif-4000这个版本的slash，我从命令行上看到2个块miss就会被slash，建议正式版本谨慎考虑这个数值。

## Proposal（提议）
 
 

目前sif-4000这个版本的slash，我从命令行上看到2个块miss就会被slash，建议正式版本谨慎考虑这个数值。

____
#### For Admin Use（管理员专用）
 - [x] Not duplicate issue
 - [ ] Appropriate labels applied
 - [ ] Appropriate contributors tagged
 - [ ] Contributor assigned/self-assigned

**Comment by yangyanqing** [comment]
感谢您的建议！
在测试网阶段，少量块即可触发 slash 可缩短异常测试等待时间，主网上线的时候会综合考虑各种因素后选择合适的参数的。
