### ISSUE TITLE
建议浏览器增加一些针对验证人的信息

### ISSUE THREAD

**Issue by wjdfx** [hashgard/testnets#16]
## Summary（摘要）
 
 

建议浏览器增加一些针对验证人的信息，有些数据对验证人来讲挺重要的。

## Proposal（提议）
 
 

增加的一些信息包括验证人miss了多少个块，被slash了几次，可以使用第三方的，例如 ,genesis lab 或者 bigdipper 之类的，也可以鼓励社区来建立。

____
#### For Admin Use（管理员专用）
 - [x] Not duplicate issue
 - [ ] Appropriate labels applied
 - [ ] Appropriate contributors tagged
 - [ ] Contributor assigned/self-assigned

**Comment by hashgard-victor** [comment]
我们将在下一个版本针对验证人做更多的信息展示，另外由于目前浏览器是直接读取链上数据而非「链上数据+中心化数据库」，因此无法完整展现所有关于验证人的信息，但随着研发的推进，此问题将在日后的版本中更新，感谢提交。
