### ISSUE TITLE
ERROR: Not enough amount

### ISSUE THREAD

**Issue by wjdfx** [hashgard/testnets#29]
## Summary of Bug （缺陷概述）
 

在执行 sf5001测试任务的：
hashgardcli box deposit-to boxab3jlxpt2ql 200 --from=C
时出现以下报错：
ERROR: Not enough amount

查看C账号地址(gard1333yup87r4t8w0sap4rq9zmm5z28z4fms8zsqp)有 TokenA，

在 21个任务执行：hashgardcli box deposit-to boxab3jlxpt2ql 100 --from=C
是可以成功的，

但是在22个任务的：hashgardcli box deposit-fetch boxab3jlxpt2ql 100 --from=C
之后再执行：
hashgardcli box deposit-to boxab3jlxpt2ql 100 --from=C
就会报错：ERROR: Not enough amount

## Steps to Reproduce （复现步骤）
 
 

____
#### For Admin Use （管理员专用）
 - [ ] Not duplicate issue
 - [ ] Appropriate labels applied
 - [ ] Appropriate contributors tagged
 - [ ] Contributor assigned/self-assigned

**Comment by xiazhiming** [comment]
这个不是bug 是没有足够的代币
