### ISSUE TITLE
sif-2000 Testnet任务

### ISSUE THREAD

**Issue by StrawberryFlavor** [hashgard/testnets#3]

**Comment by StrawberryFlavor** [comment]
GitHub ID: StrawberryFlavor
Task 1: http://106.12.132.153:26657/status
Task 2: gardvaloper19rcglx2mdxyvyttku0v3qyzlpwnvnj2hvsgmpx
Task 3: B173CCA3DBD9E3EC65E0669EDA8240BA3FDA79D4F658E98CCE54D2D37D57E0A9
Task 4: 
Task 5: 241070C68C17CE465CA108E5916B6C5C78BD19201DCDFD06F177C91A6F9D0087
Task 6: 47E6FEEDFDE029057C251998923B7F1854D6410008B567C79F1E3C60C199607B

**Comment by 101615** [comment]
GitHub ID: 101615
Task 1: http://113.111.5.97:26657/status
Task 2: gardvaloper152u2epm3rqs55tgyv8s3uqe73zfurwpvsgny9x
Task 3: 10B10B4C4F3A5145CDA4A0C9474F65A5A79F15CC17CDA2FB24C0BF59E1921142
Task 4: DD84D8EF4C6173B59F544D6B897EDA5F29343310D9C0981E6B8BC8304C6FD9FB
Task 5: 4455120E42808364CAEC80161C60088162B10D26661C1E50DBD092C4D2E88B38
Task 6: DE6E0BF00E1A361161EEFF121899C13F2FCED4261F5984FBD2885A0CA8216C40

**Comment by Fliex1989** [comment]
GitHub ID: Fliex1989
Task 1: http://60.191.102.218:26657/status
Task 2: gardvaloper1mnhhthv6uu8vv7fsrsxqvpmfv7jwydgf6775kg
Task 3: 7979E0F9049F39F2EE1F1095EB8FFEAF3230F29EAD78C7BFD45E07777A9629A1
Task 4: 58706BB167AE18C95DF6E777E811C398F16891E687CFC62BFD4B1CBC12426BBF
Task 5: E49489ED8ACA57585A9A229F66E2366FE492E6013DE2BB2F36453FE4AEFF9A7B
Task 6: 96B3D4F3459E669FF3739F9C278B36AB81A269FD842559640C76BAA18BDE2EFF

**Comment by wayway88** [comment]
GitHub ID: wayway88   
Task 1: http://61.140.169.68:26657/status
Task 2: gardvaloper1w0ry0jp0laxvz3v6r8kwkd884sdecjkv3l3uam
Task 3: 54AF590A0CD387AD9347CF66DE421A16123F7CECF56E2185C002733C2272C9D7
Task 4: A851FFC20F57D150B27BD355144270BFCC1C8C4A51E52E14B46074F07DFB65D2
Task 5: D1580ED806DC13A5825A6C008780B019C60E951CA965078D95C9272234578BAD
Task 6: 2631BD18D617F1206B9FDDCA96876EE22808B694606B79291EFC164B1D99111D

**Comment by Peoley199** [comment]
GitHub ID: Peoley199
Task 1: http://61.130.11.178:26657/status
Task 2: gardvaloper1wt4k4v25phynw7p3mdtw2aw7dgjgr0pxg6t96z
Task 3: AF23A61186051A150DF31D39DDCDEE2EBD70D4C79ACDA534DA91C7612A227159
Task 4: 3F3040244CD86B8992D7670CF2F9675C1FF20B8AC65513A8B43F684BFAC1A198
Task 5: FC84B445E0EBB1BBCF0E2D781562FBD8FB99A2D3501C31171C96FC31E7497DC1
Task 6: 2EDE185D68AAFEE6B0910A1A2D51648DBA4384D863F254F843956BD724042AB1
