### ISSUE TITLE
"StartTime is not a valid timestamp\  吸纳存款开始时间不能是已经过去的时间，而我需要存款盒子立即生效

### ISSUE THREAD

**Issue by Peoley199** [hashgard/testnets#31]
## Summary（摘要）
 
 
需要存款盒子立即生效

## Problem Definition（需求来源）

需要存款盒子立即生效
存款开始时间可以是已经过去的时间
暂不清楚

## Proposal（提议）
 
 
存款开始时间可以是已经过去的时间

____
#### For Admin Use（管理员专用）
 - [ ] Not duplicate issue
 - [ ] Appropriate labels applied
 - [ ] Appropriate contributors tagged
 - [ ] Contributor assigned/self-assigned

**Comment by joek899** [comment]
was there a solution to this?
