### ISSUE TITLE
在 hashgard 无法启动

### ISSUE THREAD

**Issue by runrun88** [hashgard/testnets#45]
## Summary of Bug （缺陷概述）
 
 
在hashgard start后，大约同步区块到 41871 高度出错。
panic: ERROR:
Codespace: issue
Code: 18
Message: "Can not transfer in coin174876e841 to gard1kjvtmapa2kwpjdzcu6aqhl6gufrjlpduhrqlqt"
![image](https://user-images.githubusercontent.com/39163285/62335838-00d38380-b500-11e9-88a4-bf6f8fdfc651.png)

## Steps to Reproduce （复现步骤）
 
 

____
#### For Admin Use （管理员专用）
 - [ ] Not duplicate issue
 - [ ] Appropriate labels applied
 - [ ] Appropriate contributors tagged
 - [ ] Contributor assigned/self-assigned

**Comment by runrun88** [comment]
这句 transfer 很诡异。我们根本就没有 执行过 这个操作

**Comment by StrawberryFlavor** [comment]
Please replace the latest version
