### ISSUE TITLE
多签转账的时候，广播交易失败

### ISSUE THREAD

**Issue by jeromelinjianlong** [hashgard/testnets#8]
C:\Users\Administrator>hashgardcli bank broadcast sign.json -o=json --indent
{
 "height": "0",
 "txhash": "02520956F0E8D2887AD582E11ECA17F37A283AC691A0C27477DC508F72F5E761"
}
ERROR: {"codespace":"sdk","code":4,"message":"signature verification failed"}

C:\Users\Administrator>

**Comment by yangyanqing** [comment]
请按照模板编辑 issue 补充细节信息，谢谢！
@jeromelinjianlong 
```
<!-- < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < ☺ 
v                            ✰  Thanks for opening an issue! ✰    
v    Before smashing the submit button please review the template.
v    Please also ensure that this is not a duplicate issue :)  
☺ > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > >  --> 

## Summary of Bug （缺陷概述）
<!-- Concisely describe the issue --> 
<!-- 请简明扼要的描述缺陷 --> 

## Steps to Reproduce （复现步骤）
<!-- What commands in order should someone run to reproduce your problem --> 
<!-- 请列举您的操作步骤以及每部操作的输出 --> 

____
#### For Admin Use （管理员专用）
 - [ ] Not duplicate issue
 - [ ] Appropriate labels applied
 - [ ] Appropriate contributors tagged
 - [ ] Contributor assigned/self-assigned
```

**Comment by hashgard-victor** [comment]
#### For Admin Use （管理员专用）
 - [ ] Not duplicate issue
 - [x] Appropriate labels applied
 - [ ] Appropriate contributors tagged
 - [ ] Contributor assigned/self-assigned

#### The Reason (故障原因）
cosmos程序执行多签时未做chain-id的校验，故我们复用该模块的时候也出现该状况

#### The Solution （解决方案）
![image](https://user-images.githubusercontent.com/37863845/54738679-2e263180-4bf0-11e9-821e-795c8b766572.png)
在每次sign和multisign时都手动指定下 —chain-id sif-3001
