### ISSUE TITLE
一直同步节点，但是节点状态一直是false

### ISSUE THREAD

**Issue by jeromelinjianlong** [hashgard/testnets#9]
一直同步节点，但是节点状态一直是false

**Comment by yangyanqing** [comment]
请按照模板编辑 issue 补充细节信息，谢谢！
@jeromelinjianlong 

 

## Summary of Bug （缺陷概述）
 
 

## Steps to Reproduce （复现步骤）
 
 

____
#### For Admin Use （管理员专用）
 - [ ] Not duplicate issue
 - [ ] Appropriate labels applied
 - [ ] Appropriate contributors tagged
 - [ ] Contributor assigned/self-assigned

**Comment by jeromelinjianlong** [comment]
## Summary of Bug （缺陷概述）
 
 
执行hashgard start命令，同步区块，同步完成后，去https://www.gardplorer.io/validator查询我的节点，发现ACTIVE状态竟然是FALSE

## Steps to Reproduce （复现步骤）
 
 
步骤：
1、执行hashgard start命令
2、执行hashgardcli status命令，"catching_up":false表示同步完成
3、去https://www.gardplorer.io/validator查询我的节点

**Comment by hashgard-victor** [comment]
#### For Admin Use （管理员专用）
 - [x] Not duplicate issue
 - [x] Appropriate labels applied
 - [ ] Appropriate contributors tagged
 - [x] Contributor assigned/self-assigned
#### Reason （问题原因）
没有执行unjail操作，节点下线导致被关小黑屋
#### Solution (解决手段）
请执行unjail操作
`hashgardcli slashing unjail --from=${your_wallet_name} --chain-id=sif-3001`
